# -*- coding: utf-8 -*-
"""Mental_Health_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RS981ksAE5txn-VPVhAb1k6wvvd_sRnb

#**1. Import Libraries**
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""# **2. Load the Dataset**"""

df = pd.read_csv('Student Social Media And Mental Health Impact.csv')

df.head()

"""# **3. Basic Data Understanding**"""

#Looking for number of rows and columns.
df.shape

from google.colab import drive
drive.mount('/content/drive')

df.isnull().sum()

df.duplicated().sum()

df.info()

df.describe()

"""#**4. Exploratory Data Analysis (EDA)**

We'll keep this focused — six plots, each answering one specific question about the data, not a wall of charts for the sake of it.
"""



"""### **4.1 — Distribution of the target (Mental_Health_Score)**"""

sns.histplot(df['Mental_Health_Score'], kde=True)

"""### **4.2 — Correlation heatmap**

Which numeric features actually move together with the target?
"""

sns.heatmap(df.corr(numeric_only=True), annot=True)

"""###**4.3 — Stress Level vs Mental Health Score**

*   Does higher stress genuinely come with a lower score?



"""

df.columns

df['Stress_Level'].unique()

order = ['Low', 'Medium', 'High', 'Very High']
plt.figure(figsize=(10,5))
sns.boxplot(x='Stress_Level', y='Mental_Health_Score',data=df, order=order)

sns.barplot(df,y=df['Mental_Health_Score'],x=df['Stress_Level'],palette='coolwarm',order=order)

sns.countplot(x=df['Stress_Level'],order=order)

"""###**4.4 — Daily Usage Hours vs Mental Health Score**

Does more time on social media relate to a lower score?
"""

sns.scatterplot(df,x='Avg_Daily_Usage_Hours',y= 'Mental_Health_Score')

"""###**4.5 — Sleep Hours vs Mental Health Score**

*   Sleep is one of the most commonly cited mental health factors — does the data back that up?



"""

sns.scatterplot(x='Sleep_Hours_Per_Night', y='Mental_Health_Score', data=df)

"""###**4.6 — Most Used Platform (count)**

* A quick look at which platforms are most common in our dataset.




"""

df['Most_Used_Platform'].value_counts()

plt.figure(figsize=(15,6))
sns.countplot(x=df['Most_Used_Platform'],order=df['Most_Used_Platform'].value_counts().index)

"""#  **Checking Outliers**"""

num_features = df.select_dtypes(include='number') #int64 or float64
Q1  = num_features.quantile(0.25)
Q3  = num_features.quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = (num_features < lower_bound) | (num_features > upper_bound)
print(outliers.sum())

"""# **5. Data Cleaning**



* Two real issues to fix here — everything else in this dataset is already clean, so we don't manufacture cleaning steps that aren't needed.



"""

df.describe()

#1. To drop duplicates
df = df.drop_duplicates()

#2. Converting negative or unrealitstic value to realistic value
df['Physical_Activity_Hours'] = df['Physical_Activity_Hours'].clip(lower=0)

"""**📌 Why clip(lower=0) and not dropping the row: the rest of that student's data (age, study hours, stress level, etc.) is still valid and useful — throwing away the whole row over one bad value wastes good data. Clipping caps the impossible value at the nearest realistic one (0 hours) without discarding everything else about that student.**"""

df.shape

df.describe()

"""# **6. Skewness**
**What skewness is:** a measure of how lopsided a numeric column's distribution is. A value near 0 means roughly symmetric (bell-shaped); a large positive or negative value means the data leans heavily to one side, with a long tail.

**Why it matters:** models like Linear Regression assume features are roughly well-behaved. A heavily skewed column (think: a long tail of extreme values) can quietly drag the model's predictions in that direction. Tree-based models like Random Forest don't care about skew — but since we're also training a Linear Regression baseline, it's worth fixing.
"""

sns.histplot(df['Mental_Health_Score'],kde=True)

df.skew(numeric_only = True)
# near to 0 -> Centralized (0.01, 0.002)
# negative -> Left Skewed (-1.56)
# poistive (greater than 0) -> Right Skewed (1.256)

"""# **7. Feature Engineering**
*   **One meaningful engineered feature here: grouping Country.**
*   **One meaningful engineered feature here: grouping Country.**
*   **Country has 111 unique values in this dataset ~ one-hot encoding that directly would add 110+ mostly-empty columns.**

*   **The fix: keep the top 10 most frequent countries as their own category, and bucket everything else into "Other". We keep the signal that matters and lose the noise that doesn't.**
"""

df['Country'].value_counts()

top_countries = df['Country'].value_counts().index[:10].tolist()
top_countries

def group_countries(country):
  if country in top_countries:
    return country
  else:
    return 'Other'

#new_country = []

#for country in df['Country']:
#    if country in top_countries:
#        new_country.append(country)++++
#    else:
#        new_country.append('Other')

#df['Country_new'] = new_country

df['Grouped_country'] = df['Country'].apply(group_countries)

df['Grouped_country'].value_counts()

"""**📌 Result: we went from 111 raw categories down to 11 manageable ones (10 countries + "Other").**

# **8. Encoding Strategy**

*  Before we jump into code, let's decide how each categorical column should be encoded — this decision matters more than the code itself.
*  Stress_Level → Ordinal Encoding. Its categories have a real, meaningful order: Low < Medium < High < Very High. We already saw in EDA (section 4.3) that the score drops step by step as stress increases — encoding it as 0, 1, 2, 3 preserves that order for the model.
* Gender, Academic_Level, Most_Used_Platform, Purpose_Of_Use, Country_Grouped → One-Hot Encoding. These categories have no natural order — "Instagram" isn't "greater than" "LinkedIn". One-hot encoding creates a separate 0/1 column per category so the model doesn't accidentally assume a false ranking.
"""





"""# **9. Train-Test Split**
*  **Common ratios:** 80/20 or 70/30 are both standard. We'll use an 80/20 split here — with 5,000 rows, that still leaves 1,000 rows for a solid, reliable test.
"""

df.columns

df.head()

from sklearn.model_selection import train_test_split

skwewd_col         = ['Study_Hours']
other_numeric_cols = ["Age", "Avg_Daily_Usage_Hours", "Daily_Unlocks","Physical_Activity_Hours",
                      "Sleep_Hours_Per_Night"]
ordinal_col        = ['Stress_Level']
normal_col         = ["Gender", "Academic_Level", "Most_Used_Platform", "Purpose_Of_Use", "Grouped_country"]

feature_col = skwewd_col + other_numeric_cols + ordinal_col + normal_col
X = df[feature_col]
y = df['Mental_Health_Score']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)

"""# **10. Preprocessing using ColumnTransformer**
* Our columns need different treatment:

*  Study_Hours (the skewed one) → impute → log1p transform → scale
*  The other numeric columns → impute → scale (no skew to fix)
*  Stress_Level → impute → OrdinalEncoder with an explicit order
*  The nominal columns → impute → OneHotEncoder
"""

from sklearn import pipeline
from inspect import formatannotation
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import FunctionTransformer,StandardScaler,OrdinalEncoder,OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn import set_config

set_config(display='diagram')

#1. Skewed features
skew_pipeline = Pipeline(steps=[
    ('log_transform', FunctionTransformer(np.log1p)),
    ('scale', StandardScaler())

])

#2. Numeric Features
plain_numeric_pipeline = Pipeline(steps=[
    ('scale',StandardScaler())
])

#3. Ordinal
ordinal_pipeline = Pipeline(steps=[
    ('encode', OrdinalEncoder(categories=[['Low', 'Medium', 'High', 'Very High']]))
])

#4. Nominal Features
nominal_pipeline = Pipeline(steps=[
    ('encode', OneHotEncoder(handle_unknown="ignore"))
])


    # (konsi_pipeline, konsa_feature)
preprocessor = ColumnTransformer(transformers=[
    ("Skewed_Pipeline", skew_pipeline, skwewd_col),
    ("Plain_Numeric",plain_numeric_pipeline, other_numeric_cols ),
    ('Ordinal', ordinal_pipeline, ordinal_col),
    ('Normal', nominal_pipeline, normal_col)
])


preprocessor

"""# **11. Build a Pipeline**
**Why Pipeline matters:** a Pipeline chains preprocessing and the model into a single object. Calling .fit() once does both steps in the correct order, and calling .predict() on brand-new raw data automatically applies the exact same preprocessing that was used during training — no risk of forgetting a step or applying it inconsistently.

**Why companies prefer this:** when this model gets deployed (which we're doing in Part 2 with FastAPI), the API doesn't need to know anything about scaling, encoding, or log transforms — it just loads one saved pipeline object and calls .predict() on raw input. That's a huge reduction in what can go wrong in production.

We'll build two pipelines below — one per model — so we can fairly compare them.

# **12. Model Building**
We're comparing two models here because the comparison itself teaches something useful — a plain Linear Regression baseline versus a Random Forest, which can capture the non-linear patterns we spotted back in EDA (section 4.4).

### **12.1 — Baseline: Linear Regression**
"""

from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

lr_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('regressor', LinearRegression())
])

lr_pipeline.fit(X_train, y_train)
lr_preds       = lr_pipeline.predict(X_test)
lr_preds_train = lr_pipeline.predict(X_train)

lr_r2_testing  = r2_score(y_test, lr_preds)
lr_r2_training = r2_score(y_train, lr_preds_train)
lr_mae         = mean_absolute_error(y_test, lr_preds)

print(f"Accuracy of Training {lr_r2_training}")
print(f"Accuracy of Testing {lr_r2_testing}")
print(f'MAE {lr_mae}')

"""### **12.2 — Random Forest (default settings)**
Same preprocessor, different model at the end — that's the entire point of building the pipeline once.
"""

from sklearn.ensemble import RandomForestRegressor

rf_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('random forest', RandomForestRegressor(random_state=42))
])

rf_pipeline.fit(X_train, y_train)
rf_preds          = rf_pipeline.predict(X_test)
rf_preds_training = rf_pipeline.predict(X_train)

rf_r2_testing  = r2_score(y_test, rf_preds)
rf_r2_training = r2_score(y_train, rf_preds_training)
rf_mae         = mean_absolute_error(y_test, rf_preds)

print(f"Accuracy of Training {rf_r2_training}")
print(f"Accuracy of Testing {rf_r2_testing}")
print(f"MAE : {rf_mae}")

"""### **12.3 — Hyperparameter Tuning the Random Forest**
When tuning a Pipeline, each parameter needs to be prefixed with the step name (regressor__) so RandomizedSearchCV knows which part of the pipeline it belongs to. We use RandomizedSearchCV instead of a full grid search — it samples a fixed number of combinations instead of testing every single one, which is far faster while still finding a strong set of parameters.
"""

from sklearn.model_selection import RandomizedSearchCV

param_grid = {
    'random forest__n_estimators'       : [100,200,300],
    'random forest__max_depth'         : [5,10,15],
    'random forest__min_samples_split' : [2,5,10],
    'random forest__min_samples_leaf'  : [1,2,4]
}

random_search = RandomizedSearchCV(
    estimator=rf_pipeline,
    param_distributions=param_grid,
    n_iter = 15,
    cv = 5,
    scoring='r2',
    random_state=42,
    n_jobs =-1 #processor free
)

random_search.fit(X_train, y_train)

